name: 'Amplify CLI Deploy Action'
description: 'Deploys to Amplify using the CLI'
inputs:
  env:
    description: 'Environment'
    required: true
    default: 'dev'
runs:
  using: 'docker'
  image: 'docker://cordobeces/amplify-cli-action:v1.0.0'
  args:
    - ${{ inputs.env }}
branding:
  icon: 'activity'
  color: 'green'
